(source melpa)

(depends-on "ace-jump-mode")
(depends-on "ergoemacs-mode")
(depends-on "evil")
(depends-on "evil-args")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "evil-numbers")
(depends-on "evil-surround")
(depends-on "evil-tabs")
(depends-on "evil-visualstar")
(depends-on "key-chord")
(depends-on "pallet")
(depends-on "powerline")