(defvar current-dir (file-name-directory load-file-name)
  "Current directory") 
(defvar config-dir (expand-file-name "config" current-dir)
  "Config Directory")
(defvar hook-dir (expand-file-name "hooks" config-dir)
  "Config Directory")

(add-to-list 'load-path config-dir)
(add-to-list 'load-path hook-dir)
(require 'auto-install-packages)
(require 'ui)
(require 'editor)
(require 'keybindings)
;;hook modes
;;(add-hook LaTeX-mode-hook (turn-on-auto-fill)) 
(require 'h-latex)
